sudo: required
services:
  - docker

before_install:
  - docker build -t jbsheebs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jbsheebs/docker-react npm run test

deploy:
  # edge: master
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerReact"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-337512418887"
  bucket_path: "DockerReact"
  on:
    path: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY